//1
document.write ("Result:")
document.write ("<br>")
document.write (".......................")
document.write ("<br>")
document.write ("<br>")
var a = 10
document.write ("The value of ++a is: " + ++a)
document.write ("<br>")
document.write ("Now the value of a is: " + a)
document.write ("<br>")
document.write ("<br>")
document.write ("The value of a++ is: " + a++)
document.write ("<br>")
document.write ("Now the value of a is: " + a)
document.write ("<br>")
document.write ("<br>")
document.write ("The value of --a is: " + --a)
document.write ("<br>")
document.write ("Now the value of a is: " + a)
document.write ("<br>")
document.write ("<br>")
document.write ("The value of a-- is: " + a--)
document.write ("<br>")
document.write ("Now the value of a is: " + a)
//2
document.write ("<br>")
document.write ("<br>")
document.write ("var a = 2, b = 1;")
document.write ("<br>")
document.write ("var result = --a - --b + ++b + b--;")
document.write ("<br>")
document.write ("<br>")
document.write ("--a;" + " 1")
document.write ("<br>")
document.write ("--a - --b;" + " 1")
document.write ("<br>")
document.write ("--a - --b + ++b;" + " 2")
document.write ("<br>")
document.write ("--a - --b + ++b + b--;" + " 3")
document.write ("<br>")
document.write ("a is 1")
document.write ("<br>")
document.write ("b is 0")
document.write ("<br>")
document.write ("result is 3")